server:
  port: 1000

spring:
  data:
    redis:
      host: 101.126.19.236
      port: 6379
      database: 0
      password: 32110219miku!
  cloud:
    nacos:
      discovery:
        server-addr: 101.126.19.236:8848
#        username: nacos
#        password: nacos