server:
  port: 55
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # 不限制请求体大小

  # 日志级别
logging:
  level:
    root: info

spring:
  application:
    name: file-service
  cloud:
    nacos:
      discovery:
        server-addr: 191.126.19.236:8848
#        username: nacos
#        password: nacos